config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  get 'pages/home', :as => 'home'
  get 'pages/about', :as => 'about'
  get 'pages/portafolio', :as => 'portafolio'
  get 'pages/contacto', :as => 'contacto'
  get 'pages/blog', :as => 'blog'
  match "checkout", to: "orders#checkout", as: "checkout", via: [:get, :patch]

  mount Shoppe::Engine => "/shoppe"

  get "product/:permalink", to: "products#show", as: "product"
  post "product/:permalink", to: "products#buy", as: "buy"
  get 'products/:category_id' => 'products#index', :as => 'products'  
  get 'products/:category_id/:subcategory_id' => 'products#index', :as => 'products_sub' 
  root to: "pages#home"
  get "basket", to: "orders#show"
  
  
  post 'products/:category_id/:product_id/buy' => 'products#add_to_basket', :as => 'buy_product'
  delete 'basket/delete/:order_item_id' => 'orders#remove_item', :as => 'remove_basket_item'
  
  

end

app/views/shared/_order_items.html.erb
<div class="cart-body-elements">
   <div class="cart-items">
      <% order.order_items.each do |item| %>
      <div class="cart-item">
         <a class="cart-item-edit" href="index.html#"><i class="fa fa-pencil"></i></a>       
         <%= link_to "<i class='fa fa-times'></i>".html_safe, remove_basket_item_path(item), :method => :delete, :class => 'cart-item-delete delete ajax' %>
         <div class="media">
            <%= link_to product_path(item.ordered_item.permalink), class:"pull-left"  do %>
            <% image_tag item.ordered_item.default_image.path, :size => "50x50" %>
            <% end %> 
            <div class="media-body">
               <span class="cart-item-title"><%= item.ordered_item.full_name %></span>
               <span class="cart-item-options"></span>
               <span class="cart-item-amount"><%= item.quantity %>*<span><%= number_to_currency item.unit_price %></span></span>
            </div>
         </div>
      </div>
      <% end %>
   </div>
   <div class="cart-caption">
      <div class="cart-total text-right">Total: <span class="cart-total-value"><%= number_to_currency order.total %></span></div>
      <div class="clearfix"></div>
      <div class="center">
         <div class="space10">&nbsp;</div>
         <%= link_to 'Checkout <i class="fa fa-chevron-right"></i>'.html_safe , 
         if user_signed_in? 
         checkout_path 
         else
         new_user_registration_path
         end, :class => "beta-btn primary text-center" %>
         
      </div>
   </div>
</div>