config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  get 'pages/home', :as => 'home'
  get 'pages/about', :as => 'about'
  get 'pages/portafolio', :as => 'portafolio'
  get 'pages/contacto', :as => 'contacto'
  get 'pages/blog', :as => 'blog'
  match "checkout", to: "orders#checkout", as: "checkout", via: [:get, :patch]

  mount Shoppe::Engine => "/shoppe"

  get "product/:permalink", to: "products#show", as: "product"
  post "product/:permalink", to: "products#buy", as: "buy"
  get 'products/:category_id' => 'products#index', :as => 'products'  
  get 'products/:category_id/:subcategory_id' => 'products#index', :as => 'products_sub' 
  root to: "pages#home"
  get "basket", to: "orders#show"
  
  
  post 'products/:category_id/:product_id/buy' => 'products#add_to_basket', :as => 'buy_product'
  delete 'basket/delete/:order_item_id' => 'orders#remove_item', :as => 'remove_basket_item'
  
  

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include ApplicationHelper 

  before_filter do
    if params[:category_id]
      @product_category = Shoppe::ProductCategory.where(:permalink => params[:category_id]).first!
    end
    if @product_category && params[:product_id]
      @product = @product_category.products.where(:permalink => params[:product_id]).active.first!      
    end
  end
  
  def index
	  @products = Shoppe::Product.root.ordered.includes(:product_categories, :variants)

	  @products = @products.group_by(&:product_category)
    @products = @products.select { |k,v| belongs_permalink(k.permalink,params[:category_id],params[:subcategory_id])}     

	end
  
  def filter
    @products = Shoppe::Product.active.with_attributes(params[:key].to_s, params[:value].to_s)
  end
  
  def categories
    @product_categories = Shoppe::ProductCategory.ordered
  end
  
  def show
    @product = Shoppe::Product.root.find_by_permalink(params[:permalink])
    @bestSellers = bestSellers
    @products_related=  products_related
    @attributes = @product.product_attributes.public.to_a
  end
   
  def add_to_basket
    product_to_order = params[:variant] ? @product.variants.find(params[:variant].to_i) : @product
    current_order.order_items.add_item(product_to_order, params[:quantity].blank? ? 1 : params[:quantity].to_i)
    respond_to do |wants|
      wants.html { redirect_to request.referer }
     # wants.json { render :json => {:added => true} }
     wants.json do
          current_order.reload
          render :json => {:status => 'complete', :items => render_to_string(:partial => 'shared/order_items.html', :locals => {:order => current_order})}
        end
    end
  rescue Shoppe::Errors::NotEnoughStock => e
    respond_to do |wants|
      wants.html { redirect_to request.referer, :alert => "We're sorry but we don't have enough stock to add that many products. We currently have #{e.available_stock} item(s) in stock. Please try again."}
      wants.json { render :json => {:error => 'NotEnoughStock', :available_stock => e.available_stock}}
    end
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<div class="container">
   <div id="content">
      <div class="row">         
         <div class="col-sm-9 main-content pull-right">
            
            <div class="space10">&nbsp;</div>
           
            <div class="beta-products-list">
               <% @products.each do |category, products| %>
               <h4><%= category.name %></h4>
               <div class="beta-products-details">
                  <p class="pull-left"><%= category.products.count %> productos | <a class="verMas" id="category-<%= category.permalink %>">Ver más</a> </p>                  
                  <div class="clearfix"></div>
               </div>
               <div class="row">  
                  <% products.each_with_index do |product, index| %>
                  
                     <div class="<% if index + 1 > 3 %>hideProduct<% end %>" id="category-<%= category.permalink %>">
                     <div class="col-sm-4 wow fadeInDown">
                        <div class="single-item">
                           <div class="single-item-header">
                              <% if product.default_image %>
                                <%= image_tag product.default_image.path, :size => "262x311" %>
                              <% end %> 
                           </div>
                           <div class="single-item-body">
                              <p class="single-item-title"><%= product.name %></p>
                              <p class="single-item-price">
                                 <span><%= number_to_currency product.price %></span>
                              </p>
                           </div>
                           <div class="single-item-caption">
                              <%  if product.orderable? && product.stock>0 %>
                                <%= link_to "<i class='fa fa-shopping-cart'></i>".html_safe, buy_product_path(product.product_category.permalink, product.permalink), :method => :post, class: "add add-to-cart pull-left"  %>
                              <% end %>
                              <%= link_to "Details <i class='fa fa-chevron-right'></i>".html_safe, product_path(product.permalink), class: "beta-btn primary"  %>
                              <div class="clearfix"></div>
                           </div>
                           <% if (index + 1) % 3 == 0 || (index + 1) == category.products.count %>
                              <div class="space50">&nbsp;</div>
                           <% end %>
                        </div>
                     </div>
                     </div>                   
                  <% end %>                                                        
               </div>
               <% end %>

            </div>
            <!-- .beta-products-list -->
            <div class="space50">&nbsp;</div>      
           
          
         </div>
         <!-- .main-content -->         
         <div class="col-sm-3 aside">            
         </div>
   </div>
   <!-- #content -->
</div>
<!-- .container -->
</div>

app/views/products/show.html.erb
<div class="container">
	<div id="content">
		<div class="row">
			<div class="col-sm-9">

				<div class="row">
					<div class="col-sm-4">
						<% if @product.default_image %>
                           <%= image_tag @product.default_image.path, :size => "262x311" %>
                     	<% end %>						
					</div>
					<div class="col-sm-8">
						<div class="single-item-body">
							<p class="single-item-title"><%= @product.name %></p>
							<p class="single-item-price">
								<span class="beta-sales-price"><%= number_to_currency @product.price %></span>
							</p>
						</div>

						<div class="woocommerce-product-rating" >
							
							<span class="color-gray">Stock (<%= @product.stock %>)</span>
							<table>
							<% @attributes.each do |attribute| %>
							<tr>
								<th>
									<span class="color-gray"><%= attribute.key %>:&nbsp;&nbsp;</span>
								</th>
								<td>
									<span class="color-gray"><%= attribute.value %></span>
								</td>
							</tr>
							<% end %>
							</table>
						</div>

						<div class="clearfix"></div>
						<div class="space20">&nbsp;</div>

						<div class="single-item-desc">
							<p><%= @product.description %></p>
						</div>
						<div class="space20">&nbsp;</div>

						<p>Options:</p>
						<div class="single-item-options">
							<select class="wc-select" name="size">
								<option>Size</option>
								<option value="XS">XS</option>
								<option value="S">S</option>
								<option value="M">M</option>
								<option value="L">L</option>
								<option value="XL">XL</option>
							</select>
							<select class="wc-select" name="color">
								<option>Color</option>
								<option value="Red">Red</option>
								<option value="Green">Green</option>
								<option value="Yellow">Yellow</option>
								<option value="Black">Black</option>
								<option value="White">White</option>
							</select>
							<select class="wc-select" name="color">
								<option>Qty</option>
								<option value="1">1</option>
								<option value="2">2</option>
								<option value="3">3</option>
								<option value="4">4</option>
								<option value="5">5</option>
							</select>							
							<div class="single-item-caption">
								 <%  if @product.orderable? && @product.stock>0 %>
                                 <%= link_to "<i class='fa fa-shopping-cart'></i>".html_safe, buy_product_path(@product.product_category.permalink, @product.permalink), :method => :post, class: "add add-to-cart pull-left"  %>
                                 <% end %>							     
							   <div class="clearfix"></div>	
						    </div>	
						</div>
					</div>
				</div>

				<div class="space40">&nbsp;</div>
				<div class="woocommerce-tabs">
					<ul class="tabs">
						<li><a href="product.html#tab-description">Description</a></li>
						<li><a href="product.html#tab-reviews">Reviews (0)</a></li>
					</ul>

					<div class="panel" id="tab-description">
						<p>Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet.</p>
						<p>Consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequaturuis autem vel eum iure reprehenderit qui in ea voluptate velit es quam nihil molestiae consequr, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? </p>
					</div>
					<div class="panel" id="tab-reviews">
						<p>No Reviews</p>
					</div>
				</div>
				<div class="space50">&nbsp;</div>
				<div class="beta-products-list">
					<h4>Productos Relacionados</h4>

					<div class="row">			

						<% @products_related.each do |product| %>					
							<div class="col-sm-4">
								<div class="single-item">
									<div class="single-item-header">
										<% if product.default_image %>
				                           <%= image_tag product.default_image.path, :size => "262x311" %>
				                     	<% end %>										
									</div>
									<div class="single-item-body">
										<p class="single-item-title"><%= product.name %></p>
										<p class="single-item-price">
											<span class="beta-sales-price"><%= number_to_currency product.price %></span>
										</p>
									</div>
									<div class="single-item-caption">
										<%= link_to "<i class='fa fa-shopping-cart'></i>".html_safe, buy_product_path(product.product_category.permalink, product.permalink), :method => :post, class: "add add-to-cart pull-left"  %>
										<%= link_to "Detalle <i class='fa fa-chevron-right'></i>".html_safe, product_path(product.permalink), class: "beta-btn primary"  %>								
										<div class="clearfix"></div>
									</div>
								</div>
							</div>						
						<% end %>  




						
					</div>
				</div> <!-- .beta-products-list -->
			</div>
			<div class="col-sm-3 aside">
				

				<div class="widget">
				   <h3 class="widget-title">Mas vendidos</h3>
				   <div class="widget-body">
				      <div class="beta-sales beta-lists">
				      <% @bestSellers.each do |product| %>
				         <div class="media beta-sales-item">                        
				            <% if product.default_image %>
				              <%= link_to product_path(product.permalink), class:"pull-left"  do %>
				                 <% image_tag product.default_image.path, :size => "55x58" %>
				              <% end %>                               
				            <% end %>                         
				            <div class="media-body">
				               <%= product.name %>
				               <span class="beta-sales-price"><%= number_to_currency product.price %></span>
				            </div>
				         </div>
				      <% end %>
				      </div>
				   </div>
				</div>
				<!-- best sellers widget -->



				<div class="widget">
					<h3 class="widget-title">Twitter Feeds</h3>
					<div class="widget-body">
						<div class="twitter-feed beta-lists">
							<div class="tweet">
								<i class="fa fa-twitter"></i>
								<div class="tweet-body">
									<p><a href="product.html#">@ShopaHolic</a> Proin feugiat mattis ante sed adipiscing velit sodales.</p>
									<small class="tweet-time">25 Minutes ago</small>
								</div>
							</div>
							<div class="tweet">
								<i class="fa fa-twitter"></i>
								<div class="tweet-body">
									<p>Proin feugiat mattis ante sed adipiscing velit sodales. <a href="product.html#">http://shopaholic.com</a></p>
									<small class="tweet-time">25 Minutes ago</small>
								</div>
							</div>
						</div>
					</div>
				</div> <!-- twitter feeds widget -->

				<div class="widget">
					<h3 class="widget-title">Tags</h3>
					<div class="widget-body">
						<div class="beta-tags">
							<a href="blog_with_2sidebars_type_e.html">Amazing</a>
							<a href="blog_with_2sidebars_type_e.html">Shop</a>
							<a href="blog_with_2sidebars_type_e.html">Themes</a>
							<a href="blog_with_2sidebars_type_e.html">Clean</a>
							<a href="blog_with_2sidebars_type_e.html">Responsiveness</a>
							<a href="blog_with_2sidebars_type_e.html">Multipurpose</a>
							<a href="blog_with_2sidebars_type_e.html">Creative</a>
							<a href="blog_with_2sidebars_type_e.html">Brands</a>
							<a href="blog_with_2sidebars_type_e.html">Categories</a>
						</div>
					</div>
				</div> <!-- tags cloud widget -->
			</div>
		</div>
	</div> <!-- #content -->
</div> <!-- .container -->